name: Populate Depot json

on:
  release:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: LemLib/pros-depot@dbaa18709f8239296212a47328a221290bd31fd8
        with:
          token: ${{ github.token }}
          repo: alexDickhans/command-based-pros
          readable-json: true
